[versions]
kotlinVersion = "1.7.22"
ktLintVersion = "11.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlin-lint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLintVersion" }
kotlin-lint-idea = { id = "org.jlleitschuh.gradle.ktlint-idea", version.ref = "ktLintVersion" }